version: "3"

services:
  otp-data-downloader:
    image: bash
    container_name: otp-data-downloader
    volumes:
      - ./:/working_dir
    working_dir: /working_dir
    entrypoint: ["bash", "./docker/otp/scripts/fetch-data.sh"]
    environment:
      ODPT_ACCESS_TOKEN: ${ODPT_ACCESS_TOKEN}
      ODPT_CHALLENGE_ACCESS_TOKEN: ${ODPT_CHALLENGE_ACCESS_TOKEN}

  otp:
    image: opentripplanner/opentripplanner:2.6.0_2024-07-11T01-17
    container_name: otp
    environment:
      JAVA_OPTS: ${OTP_MEMORY_LIMIT}
    volumes:
      - ./docker/otp:/var/opentripplanner
    command: ${OTP_OPTIONS}
    ports:
      - "${OTP_SERVER_PORT}:8080"
    depends_on:
      otp-data-downloader:
        condition: service_completed_successfully
