version: "3"

services:
  otp-data-downloader:
    image: alpine
    container_name: otp-data-downloader
    env_file:
      - ./docker/.env
    volumes:
      - ./:/working_dir
    working_dir: /working_dir
    entrypoint: ["./docker/otp/scripts/fetch-data.sh"]
    environment:
      API_KEY: ${ODPT_CHALLENGE_ACCESS_TOKEN}

  otp-builder:
    image: opentripplanner/opentripplanner:2.6.0_2024-07-11T01-17
    container_name: otp-builder
    env_file:
      - ./docker/.env
    environment:
      JAVA_OPTS: ${OTP_MEMORY_LIMIT}
    volumes:
      - ./docker/otp:/var/opentripplanner
    entrypoint: ["./docker/otp/scripts/build.sh"]
    depends_on:
      otp-data-downloader:
        condition: service_completed_successfully

  otp:
    image: opentripplanner/opentripplanner:2.6.0_2024-07-11T01-17
    container_name: otp
    env_file:
      - ./docker/.env
    environment:
      JAVA_OPTS: ${OTP_MEMORY_LIMIT}
    volumes:
      - ./docker/otp:/var/opentripplanner
    command: >
      --load --serve
    ports:
      - "${OTP_SERVER_PORT}:8080"
    depends_on:
      otp-builder:
        condition: service_completed_successfully
