version: "3"

services:
  downloader:
    image: alpine
    volumes:
      - ./:/working_dir
    working_dir: /working_dir
    entrypoint: ["sh", "./initial.sh"]
    environment:
      - API_KEY=${ODPT_CHALLENGE_ACCESS_TOKEN}

  otp:
    image: opentripplanner/opentripplanner:2.6.0_2024-07-11T01-17
    container_name: otp
    environment:
      - JAVA_OPTS=-Xmx8G
    volumes:
      - ./otp:/var/opentripplanner
    command: >
      --build --save --serve
    ports:
      - "8080:8080"
    depends_on:
      downloader:
        condition: service_completed_successfully
