import { TanStackRouterVite } from '@tanstack/router-vite-plugin'
import react from '@vitejs/plugin-react-swc'
import { defineConfig } from 'vite'

export default defineConfig({
  define: {
    __UPDATED_YEAR__: new Date().getFullYear(),
  },
  server: {
    port: 3000,
  },
  plugins: [
    react(),
    TanStackRouterVite({
      routesDirectory: 'src/routes',
      generatedRouteTree: 'src/lib/tanstack-router/routeTree.gen.ts',
      routeFileIgnorePrefix: '.',
      semicolons: false,
      quoteStyle: 'single',
      routeTreeFileHeader: ['// biome-ignore lint: this file is auto-generated by TanStack Router'],
      routeTreeFileFooter: [],
    }),
  ],
})
